### ISSUE TITLE
Updating the parser under the new specification!

### ISSUE THREAD

**Issue by themrxcm** [jblindsay/lidario#1]
Will there be an update for the new specification LAS 1.4?
https://www.asprs.org/wp-content/uploads/2010/12/LAS_1_4_r13.pdf

**Comment by jblindsay** [comment]
Yes, eventually I will update this library to handle LAS 1.4 reading/writing. At the moment, most of my efforts have been placed in the WhiteboxTools project and I already have support for reading LAS 1.4 in there. That knowledge will be used to backport to lidario.

**Comment by themrxcm** [comment]
Great, thank you! I use your library in a new project and I would not like to abandon it due to the lack of support for LAS 1.4. I hope you update soon, thanks in advance and success!
