### ISSUE TITLE
Does this library support LAS 1.4?

### ISSUE THREAD

**Issue by hbarrett** [jblindsay/lidario#2]
I get "panic: runtime error: index out of range" when trying to access my LAS 1.4 files.
Thanks!

**Comment by jblindsay** [comment]
@hbarrett No, I'm afraid that this library doesn't currently support LAS 1.4, only LAS 1.1-1.3. The [WhiteboxTools](https://github.com/jblindsay/whitebox-tools) library does support reading 1.4 but not yet writing. However, WhiteboxTools is not developed in Go, if that is a requirement for you.
