### ISSUE TITLE
Converting Lidar .las / .laz to .tif

### ISSUE THREAD

**Issue by RitaAguiar** [jblindsay/lidario#5]
I would like to suggest a new feature to be able to convert a lidar .las / .laz to a .tif file.

**Comment by jblindsay** [comment]
That's exactly what [LidarDigitalSurfaceModel](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/lidar_tools.html#LidarDigitalSurfaceModel), [LidarIdwInterpolation](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/lidar_tools.html#LidarIdwInterpolation), [LidarRbfInterpolation](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/lidar_tools.html#LidarRbfInterpolation), [LidarSibsonInterpolation](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/lidar_tools.html#LidarSibsonInterpolation), and [LidarTinGridding](https://www.whiteboxgeo.com/manual/wbt_book/available_tools/lidar_tools.html#LidarTinGridding) do.
